[Server] Use length returned by read and fix an alignment check in pgRead
xrootd/xrootd pull request #1510
Opened 2021-09-07 12:41 UTC by smithdh

Changes XrdOssDF and XrdOucCacheIO pgRead to use the length returned by read when calculating the checksums, rather than the requested read size. Believed to fix issue #1507.

Also removes an alignment check which may have been inadvertently re-added to XrdOucCacheIO::pgRead during a rebase.

2021-09-08 04:37 UTC, abh3 commented on src/XrdOuc/XrdOucCache.cc
> -
How this check is being removed? While I agree the test for requiring all reads to be a multiple of 4K is likely to strict, for the ache all reads must be page aligned. So, at least that check should have remained.

2021-09-08 04:38 UTC, abh3 requested changes
Thank you David for catching this. An obvious and stupid mistake. That said, I did ask about the removal the the test for pgRead() as it seem at least the offset check should stay.

2021-09-10 10:58 UTC, smithdh commented
(some discussion going on by email with Andy & Matevz about the alignment check(s) in XrdOucCacheIO::pgRead)

2021-09-10 22:31 UTC, abh3 approved these changes
You are absolutely correct. Somewhere along the way we started using the CacheIO object for all IO requests, cache or not. Since pgRead and pgWrite were extended to be able to do unaligned reads and writes the change was indeed necessary.

2021-09-10 22:31 UTC, merged