[XrdCrypto,XrdSecgsi] Update min/default RSA bits to 2048
xrootd/xrootd pull request #2117
Opened 2023-10-31 15:09 UTC by amadio

2023-10-31 18:50 UTC, abh3 requested changes
Just two changes that I saw and one is a comment.  Nice job though!

2023-10-31 18:50 UTC, abh3 commented on src/XrdSecgsi/XrdSecProtocolgsi.cc
> +int    XrdSecProtocolgsi::DefBits  = 2048;
This really should come from the default value define in CryptoAux which is already included in this cc file.

2023-10-31 18:50 UTC, abh3 commented on src/XrdSecgsi/XrdSecProtocolgsi.hh
> +   int    bits;   // [c] bits in PKI for proxies [2048]
Same here, refer to the CryptoAux definition so that when it becomes 4096 we know where to look.

2023-11-01 14:21 UTC, amadio commented
@abh3 I hope the current version is in line with what you suggested.

2023-11-01 22:53 UTC, abh3 approved these changes

2023-11-01 22:54 UTC, abh3 commented
Thanks! Now we can simply change the define symbol in the future. I guess we need to wait for @esindril to complete the review.

2023-11-02 08:19 UTC, esindril approved these changes
Looks goog!

2023-11-02 08:28 UTC, amadio commented
Thanks, @esindril, I'm merging it then. Cheers,

2023-11-02 08:28 UTC, merged