XrdHttp: obfuscate token authz leaking to the logs
xrootd/xrootd pull request #2284
Opened 2024-06-13 15:43 UTC by ccaffy

Fixes #2222

Unit tests were added, one can see what the effect of the obfuscation is. I basically obfuscate 'Authorization', 'TransferHeaderAuthorization' headers and hdr2cgi 'authz='.

2024-06-14 05:14 UTC, abh3 requested changes

2024-06-14 05:14 UTC, abh3 commented on src/XrdOuc/XrdOucUtils.cc
> +      ret += " ***********";
I think we should follow Brian's suggestion of "****REDACTED**** as the substitiion string.

2024-06-14 05:14 UTC, abh3 commented on src/XrdOuc/XrdOucUtils.cc
> +          result << key << keyValueDelimiter << "************";
See comment about using a different substitution above.

2024-06-15 07:36 UTC, abh3 approved these changes
Thanks for the changes!

2024-06-17 12:15 UTC, amadio approved these changes

2024-06-17 12:15 UTC, merged