[Server] IOV_MAX can be undefined
xrootd/xrootd pull request #2294
Opened 2024-07-06 03:53 UTC by ellert

Use the same code as in other places where IOV_MAX is needed (e.g. src/XrdXrootd/XrdXrootdXeqFAttr.cc)

2024-07-06 06:23 UTC, abh3 requested changes
This is actually bery bad. Every time a read occurs we ned to do a sys_conf call. This logic should be moved to configuration time (I am not a fan of onetime as that is still an ctive test). The correct value can then be placed in a an accessible place and used therafter.

2024-07-06 15:02 UTC, ellert commented
> Every time a read occurs we ned to do a sys_conf call.

No, it is done once, After the first call the static variableisn't -1 ny more.

2024-07-09 16:11 UTC, amadio commented
How about defining `IOV_MAX` to 1024 in `XrdSysPlatform.hh` if it's not already defined? I wonder in which case it was not defined as well (and if we should include a build in CI for it).

2024-07-09 16:39 UTC, abh3 commented
That's effectively what is done but it has to be an active test because IOV_MAX might not be defined ibecause you have to use SC_Conf() to get the value. If you suggest defining the static value in  the anonymous namespace, it seems like overkill since you would have to redo the calulation everywhere SysPlatform is included and we need IOV_MAX in very few places. Making it a global static exposes you to static initialization ordering (though it's unlikely here). So, what Matias had is correct but that code is duplicated in various places. It really should be considildated into a single place. Hence my proposal which would work everywhere IOV_MAX is needed and the change where it is used is pretty trivial.

2024-07-20 06:20 UTC, ellert commented
See #2298.

2024-07-29 08:36 UTC, closed without merging