[XrdHttp] Set oss.asize if object size is known
xrootd/xrootd pull request #2378
Opened 2024-11-30 01:14 UTC by bbockelm

If the client declares the expected size of the uploaded object, then pass this information on to the OSS layer via the `oss.asize` CGI.

This is relevant for the S3 backend as the S3 protocol requires object sizes to be declared ahead of time.  If XRootD doesn't provide this information, then the S3 OSS backend has to buffer the uploaded object to know the final size, costing both in overall throughput and memory usage.

2024-12-31 19:23 UTC, bbockelm commented
Per input from @amadio in a different ticket, I re-targeted this to master.

2025-01-10 20:30 UTC, bbockelm commented
@ccaffy - since you've been working on the XrdHttp pieces, would you be able to review this?

2025-01-13 14:43 UTC, ccaffy requested changes
Thanks Brian, I tried it on my local box, it works without any problem. Just one minor thing to change if possible :)

2025-01-13 18:18 UTC, bbockelm commented on src/XrdHttp/XrdHttpReq.cc
> +  int has_query_params = 0;
Unfortunately, no: there are three states that this variable is tracking:
- We have not yet looked in the URL for the presence of query parameters (0).
- The URL has query parameters (1).
- The URL is known to _not_ have query parameters (2).

So, we need something two bits wide at least - can't be a `bool`!

If you'd still like a change, I can replace the integer with two boolean perhaps?  Or would you prefer it stay as-is?

2025-01-14 08:01 UTC, ccaffy commented on src/XrdHttp/XrdHttpReq.cc
> +  int has_query_params = 0;
Hi @bbockelm ,

OK thanks, so no need to change that logic. Perhaps rename that variable as it can be confusing for developers to read a variable name starting with `has` that is not a boolean. If you just rename that integer and put some comments (the same as you did to explain) then it's very good :)).

Thanks!

2025-01-15 18:49 UTC, bbockelm commented on src/XrdHttp/XrdHttpReq.cc
> +  int has_query_params = 0;
This refactor has been done as requested.

2025-01-16 09:00 UTC, ccaffy approved these changes
That's great, thanks for the addition of the system tests!

2025-01-27 10:44 UTC, merged