[XrdHttp] Allow static headers to be specified for browsers
xrootd/xrootd pull request #2389
Opened 2024-12-12 22:19 UTC by bbockelm

(This patch is more of a RFI -- I think all the infrastructure is in place that I can add a unit test before marking it as not a draft)

In Pelican, we want to allow users from browsers to be able to access XRootD servers (including through redirections).  However, to do this, we need to add a few extra headers to all `GET` and `OPTIONS` requests to permit redirections across sites (we hit various CORS safeguards that are reasonable for a generic webapp -- but needed for a data federation).

The existing plugin mechanism isn't sufficient because we don't want to _replace_ the XRootD handling of the requests (such as a `GET`) but rather augment it with a few static headers.

This PR adds a new configuration option, `http.staticheader`, that permits such a header to be set.  The config option has the following form:

```
http.staticheader [-verb=[GET|HEAD|...]]* header [value]
```

Here's a few examples:

```
http.staticheader -verb=OPTIONS Access-Control-Allow-Origin *
http.staticheader -verb=GET Foo Bar
http.staticheader -verb=GET Foo Baz
http.staticheader Test 1
```

- If the `-verb` is omitted then the header is set for all requests
- If the value is omitted, then the prior static header settings are unset.  Otherwise, they are additive (same header specified multiple times will cause multiple values to be sent; this is perfectly fine in HTTP-land).

So, for the example configuration above, here's the response for a simple `GET` request:

```
< HTTP/1.1 403 Forbidden
< Connection: Close
< Server: XrootD/v5.7.1-85-g42eab06b3
< Test: 1
< Foo: Bar
< Foo: Baz
< Content-Length: 36
```

2024-12-13 13:44 UTC, bbockelm commented
@amadio - do you recognize the test failures?  I'd be a bit surprised if it was due to the PR itself (as the tests appear to be over the xrootd protocol and the changes here are localized to HTTP).

2024-12-13 14:44 UTC, amadio commented
@bbockelm Yes, those are from Andy's last couple of commits. I think it's actually better to send pull requests for master, since I can merge either there or retarget to devel more easily than the other way around. And you will not see these test failures.

2024-12-13 20:27 UTC, abh3 commented
No doubt, but other than the test ending with a non-zero RC there are no other error messages. Another transient error?

2025-01-10 20:57 UTC, bbockelm commented
Ok, hearing no fundamental objections, I added an integration test and have marked this as ready for review.

2025-01-13 16:30 UTC, ccaffy requested changes
Thanks again, I found some issues under certain circumstances (see different comments)

2025-01-13 16:30 UTC, ccaffy commented on src/XrdHttp/XrdHttpProtocol.cc
> +
There's an issue with the default header case. Here's the gdb trace I had:

```
Thread 1 "xrootd" hit Breakpoint 1, XrdHttpProtocol::Config (ConfigFN=0x433d90 "/home/xrootddev/xrootd-run/xrootd-standalone/xrd_http.cfg", 
    myEnv=0x41e420 <(anonymous namespace)::theEnv>) at /home/xrootddev/xrootd/src/XrdHttp/XrdHttpProtocol.cc:1120
1120	  if (default_verb != m_staticheader_map.end()) {
Missing separate debuginfos, use: dnf debuginfo-install systemd-libs-252-32.el9_4.6.x86_64
(gdb) p m_staticheader_map
$1 = std::unordered_map with 1 element = {[""] = std::vector of length 1, capacity 1 = {{first = "test", second = "test1"}}}
(gdb) n
250113 17:02:18 1427639 Xrd_Sched: running monitor fstat inq=0
250113 17:02:18 1427639 Xrd_Sched: scheduling monitor fstat in 5 seconds
1121	    for (const auto &header_entry : default_verb->second) {
(gdb) n
250113 17:02:59 1427639 Xrd_Sched: running monitor fstat inq=0
250113 17:02:59 1427639 Xrd_Sched: scheduling monitor fstat in 5 seconds
250113 17:02:59 1427643 TLS_Refresh: CRL refresh will happen in 60 seconds.
1122	      default_static_headers += header_entry.first + ": " + header_entry.second + "\r\n";
(gdb) n
1121	    for (const auto &header_entry : default_verb->second) {
(gdb) p default_static_headers
$2 = "test: test1\r\n"
(gdb) n
250113 17:03:07 1427639 Xrd_Sched: running monitor fstat inq=0
250113 17:03:07 1427639 Xrd_Sched: scheduling monitor fstat in 5 seconds
1125	  for (const auto &item : m_staticheader_map) {
(gdb) n
1126	    auto headers = default_static_headers;
(gdb) n
1127	    for (const auto &header_entry : item.second) {
(gdb) p headers
$3 = "test: test1\r\n"
(gdb) n
250113 17:25:26 1427636 Xrd_BuffManager: Reshaper has 0K; target 2980413K
250113 17:25:26 1427639 Xrd_Sched: running monitor fstat inq=1
250113 17:25:26 1427639 Xrd_Sched: scheduling monitor fstat in 5 seconds
250113 17:25:26 1427643 TLS_Refresh: CRL refresh will happen in 60 seconds.
[New Thread 0x7ffff4543640 (LWP 1427655)]
[New Thread 0x7ffff4342640 (LWP 1427656)]
250113 17:25:26 1427639 Xrd_Sched: Now have 4 workers
250113 17:25:26 1427639 Xrd_Sched: running Job Scheduler inq=0
250113 17:25:26 1427638 Xrd_Sched: Now have 4 workers
250113 17:25:26 1427638 Xrd_Sched: running underused thread monitor inq=0
250113 17:25:26 1427638 Xrd_Sched: 4 threads; 2 idle
250113 17:25:26 1427638 Xrd_Sched: scheduling underused thread monitor in 780 seconds
250113 17:25:26 1427639 Xrd_Sched: scheduling Job Scheduler in 900 seconds
1128	      headers += header_entry.first + ": " + header_entry.second + "\r\n";
(gdb) n
1127	    for (const auto &header_entry : item.second) {
(gdb) p headers
$4 = "test: test1\r\ntest: test1\r\n"

```

2025-01-13 16:39 UTC, bbockelm commented on src/XrdHttp/XrdHttpProtocol.cc
> +  const auto iter = m_staticheaders.find(CurrentReq.requestverb);
Ah - I see what you mean.  My tests (and the unit tests below) had per-verb headers as well which hid the issue.  Seems fixable though!

2025-01-15 19:42 UTC, bbockelm commented on src/XrdHttp/XrdHttpProtocol.cc
> +      eDest.Emsg("Config", "http.staticheader requires the header to be set to be specified");
Fixed in the latest patch series.

2025-01-15 19:42 UTC, bbockelm commented on src/XrdHttp/XrdHttpProtocol.cc
> +  const auto iter = m_staticheaders.find(CurrentReq.requestverb);
Fixed in the latest patch series.

Integration test is updated to prevent a regression.

2025-01-15 19:42 UTC, bbockelm commented on src/XrdHttp/XrdHttpProtocol.cc
> +
Fixed in the latest patch series.

2025-01-15 19:43 UTC, bbockelm commented
@ccaffy - I touched up the pieces requested and adjusted the integration test accordingly.  Please re-review.

2025-01-16 09:44 UTC, ccaffy requested changes
Just one typo and then it's ready to go. I tried it on my box and it works as expected! Thanks

2025-01-16 09:44 UTC, ccaffy commented on tests/XRootD/http.sh
> +  assert_eq "$expectedHeader" "$receivedHeader" "GET is missing statically-defined Test header"
A small typo in the error message "GET" --> "HEAD" ?

2025-01-16 19:51 UTC, bbockelm commented on tests/XRootD/http.sh
> +  assert_eq "$expectedHeader" "$receivedHeader" "GET is missing statically-defined Test header"
Fixed!

2025-01-17 08:00 UTC, ccaffy approved these changes
Thanks Brian for the fixes!
I'll create an issue for @abh3 to update the xrd http documentation to document these flags behavior.

2025-01-27 14:16 UTC, bbockelm commented
@amadio - would you like me to retarget this to `master`?  I think that'll (potentially) lose the review comments from @ccaffy (though those are potentially less important now he's approved the PR) but will clean up the commit history and fix up the unit tests.

2025-01-27 14:54 UTC, amadio commented
If this doesn't depend on anything from `devel`, yes, go ahead. However, due to the nature of the changes, this will only get merged into a feature release.

2025-01-27 15:41 UTC, bbockelm commented
@amadio - sounds good!  While there are some nearby code changes, nothing from `devel` is needed for this.  I updated the PR to target `master` (which should help with the unit tests; I really like the "green checkmark") and feel free to merge into `devel` once you're ready.

2025-01-27 15:52 UTC, amadio commented
Ok, I'm marking this for 5.8.0. If there are no problems with ABI (which I will test later), I will merge this after 5.7.3 is released.

2025-02-13 14:32 UTC, amadio commented
Rebased to resolve conflicts with other merged changes that touched `http.sh` test script.

2025-02-14 09:05 UTC, merged